package i18n

// This file is generated by i18n_generator.go. DO NOT EDIT!

var en_USTranslations = map[string]string{
	"About":                             "About",
	"Are you sure you want to go back?": "Are you sure you want to go back?",
	"Are you sure you want to reset the game?": "Are you sure you want to reset the game?",
	"Close":                        "Close",
	"Create a new game":            "Create a new game",
	"Game Name":                    "Game Name",
	"Game name cannot be empty":    "Game name cannot be empty",
	"Player %s already exists":     "Player %s already exists",
	"Player Name":                  "Player Name",
	"Start!":                       "Start!",
	"Sure?":                        "Sure?",
	"You need at lease %d players": "You need at lease %d players",
	"about.content":                "# ScoreBooard - A simple Scroring Board\n\nScoreboard is a simple application to easily count points for a given game. It is developped in Go with [Fyne.io](https://fyne.io).\n\n## Information\n\nAuthor: [Patrice Ferlet](https://github.com/metal3d) aka Metal3d.\n\nYou found a bug? Go to [GitHub issues page](https://github.com/metal3d/scoreboard/issues).\n\n## Licence MIT\n\nScoreboard, a simple score board application\n\nMIT License\n\nCopyright (c) 2023 Patrice Ferlet\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the \"Software\"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\nSOFTWARE.\n",
	"add.player":                   "# Add players\n\nCreate new players for the game. You need at least %d players!\n",
	"documentation.text":           "# Scoreboard\n\nSimply press the \"Create a new game\" button to create a new game.\n\nYou'll be asked for a name for the game. Then you will add players and start to add scores.\n",
	"key string":                   "key string",
	"presentation.content":         "# Scoreboard\n\nScoreboard is a simple app to easily count points for a given game.\n",
}
