package i18n

// This file is generated by i18n_generator.go. DO NOT EDIT!

var fr_FRTranslations = map[string]string{
	"%s":                                "%s",
	"...":                               "...",
	"About":                             "À propos",
	"Are you sure you want to go back?": "Êtes vous sûr de vouloir revenir en arrière ?",
	"Are you sure you want to reset the game?": "Êtes vous sûr de vouloir réinitialiser le jeu en cours ?",
	"Close":                        "Fermer",
	"Create a new game":            "Créer un nouveau jeu",
	"Game Name":                    "Nom du jeu",
	"Game name cannot be empty":    "Le nom du jeu ne peut pas être vide",
	"Player %s already exists":     "Le joueur %s existe déjà",
	"Player Name":                  "Nom du joueur",
	"Start!":                       "C'est parti !",
	"Sure?":                        "Êtes vous sûr ?",
	"You need at lease %d players": "Vous avez besoin de %d joueurs au moins",
	"about.content":                "# ScoreBooard - Un simple tableau de scores\n\nScoreboard est une simple application de tableau de scores pour un jeu donné. Elle a été développée en Go avec la librairie [Fyne.io](https://fyne.io).\n\n## Informations\n\nAuteur: [Patrice Ferlet](https://github.com/metal3d) aka Metal3d.\n\nVous avez trouvé un bug ? Visitez [GitHub issues](https://github.com/metal3d/scoreboard/issues) (en anglais).\n\n## Licence MIT\n\nScoreboard, a simple score board application\nCopyright © 2023 Patrice Ferlet\n\nPermission is hereby granted, free of charge, to any person obtaining\na copy of this software and associated documentation files (the \"Software\"),\nto deal in the Software without restriction, including without limitation\nthe rights to use, copy, modify, merge, publish, distribute, sublicense,\nand/or sell copies of the Software, and to permit persons to whom the\nSoftware is furnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included\nin all copies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,\nEXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES\nOF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.\nIN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,\nDAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,\nTORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE\nOR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n",
	"add.player":                   "# Ajouter des joueurs\n\nCréer des joueurs, vous devez en créer au moin %d\n",
	"documentation.text":           "# Scoreboard\n\nPressez le bouton \"Créer un nouveau jeu\" pour créer un nouveau jeu.\n\nIl vous sera demandé, ensuite, de nommer le jeu. Puis vous pourrez créer des joueurs et démarrer le comptage de scores.\n",
	"key string":                   "key string",
	"presentation.content":         "# Scoreboard\n\nScoreboard est une simple application pout facilement compter les points dans un jeu.\n",
}
