package i18n

// This file is generated by i18n_generator.go. DO NOT EDIT!

// loadI18n loads all translations
func loadI18n() {
	mutex.Lock()
	defer mutex.Unlock()
	translations["en_US"] = en_USTranslations
	translations["fr_FR"] = fr_FRTranslations
}

func init() {
	loadI18n()
}
